### ISSUE TITLE
Exception reading crimes database

### ISSUE THREAD

**Issue by gadamc** [cloudant-labs/spark-cloudant#24]
Trying to follow this example:
https://github.com/cloudant-labs/spark-cloudant/blob/master/examples/ipython/python_Cloudant.ipynb

Only after removing the _design documents from the crimes database can I successfully read the data in Spark. 

When I call
```
cloudantdata.count()
```

I get a return of 372 documents (instead of 272)

And when I call
```
cloudantdata.select("properties.naturecode").show()
```

I get an exception

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-18-49a5952e2a96> in <module>()
----> 1 cloudantdata.select("properties.naturecode").show()

/usr/local/src/bluemix_ipythonspark_141/spark/python/pyspark/sql/dataframe.py in show(self, n)
    256         +---+-----+
    257         """
--> 258         print(self._jdf.showString(n))
    259 
    260     def __repr__(self):

/usr/local/src/bluemix_ipythonspark_141/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    536         answer = self.gateway_client.send_command(command)
    537         return_value = get_return_value(answer, self.gateway_client,
--> 538                 self.target_id, self.name)
    539 
    540         for temp_arg in temp_args:

/usr/local/src/bluemix_ipythonspark_141/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    298                 raise Py4JJavaError(
    299                     'An error occurred while calling {0}{1}{2}.\n'.
--> 300                     format(target_id, '.', name), value)
    301             else:
    302                 raise Py4JError(

Py4JJavaError: An error occurred while calling o75.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 34.0 failed 10 times, most recent failure: Lost task 0.9 in stage 34.0 (TID 147, yp-spark-dal09-env5-0030): java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 8
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$.convertRowWithConverters(CatalystTypeConverters.scala:348)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToCatalystConverter$4.apply(CatalystTypeConverters.scala:180)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:62)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:59)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:312)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$3.apply(SparkPlan.scala:143)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$3.apply(SparkPlan.scala:143)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1775)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1775)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:801)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1273)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1264)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1263)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1263)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:730)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1457)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1418)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
```

If I go to my cloudant account and remove all of the _design documents, this all completely works.

**Comment by HolgerKache** [comment]
@gadamc Hi Adam - we delivered the fix to filter _design documents with:
https://github.com/cloudant-labs/spark-cloudant/pull/13

The build containing that fix is available with release https://github.com/cloudant-labs/spark-cloudant/releases/tag/v1.4.1.5

Unfortunately, the release available to the Spark Service on Bluemix is still based on v1.4.1.4 and an update has been requested. ETA for that update is not until early January.

In the meantime, if you run the same tutorial with Scala you can use the `%AddJar -f https://github.com/cloudant-labs/spark-cloudant/releases/download/v1.4.1.5/cloudant-spark.jar` command to force the load of the latest version in your kernel. 

That command won't be available for the Python tutorial, however. For the Python tutorial you did the right thing by deleting the _design documents manually.

**Comment by snowch** [comment]
Can a note be added to the tutorial to save developers spending their time on something that won't work yet? https://developer.ibm.com/clouddataservices/docs/spark/get-started/use-python-notebook-to-load-cloudant-data-into-spark/

**Comment by brianewilkins** [comment]
I have got the same error when running the tutorial while working on FogBugz 59108.
The customer  in FogBugz 59108 may be getting the same error too (but I cannot be sure as the customer has not stated explicitly what error they are getting).

**Comment by HolgerKache** [comment]
I have changed https://education.cloudant.com/crimes to no longer contain any _design documents. That will eliminate the problem in the short term (until we have the new v1.4.1.5 contained in the Spark service on Bluemix)
