### ISSUE TITLE
cannot access design document view name

### ISSUE THREAD

**Issue by webe3** [cloudant-labs/spark-cloudant#64]
The following works for me when I just use the database name:

database = 'databasename'

cloudantdata_df = sqlContext.read.format("com.cloudant.spark").\
option("cloudant.host", host).\
option("cloudant.username", username).\
option("cloudant.password", password).\
load(database)

cloudantdata_df.printSchema()

However, when I try to load a particular design document and view name using the format like:

database = 'databasename/_design/analytics/_view/invBA'

I get the following java exception:

Py4JJavaError: An error occurred while calling o54.load.
: java.lang.RuntimeException: Database databasename/_design/analytics/_view/invBA request error: {"error":"method_not_allowed","reason":"Only GET,POST,HEAD allowed"}

	at com.cloudant.spark.common.JsonStoreDataAccess.getQueryResult(JsonStoreDataAccess.scala:176)
	at com.cloudant.spark.common.JsonStoreDataAccess.getMany(JsonStoreDataAccess.scala:85)
	at com.cloudant.spark.DefaultSource.create(DefaultSource.scala:114)
	at com.cloudant.spark.DefaultSource.createRelation(DefaultSource.scala:100)
	at com.cloudant.spark.DefaultSource.createRelation(DefaultSource.scala:94)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:785)

Is there a way to look at a particular design document view name?

**Comment by mayya-sharipova** [comment]
@webe3  README.md has configuration settings how to work with views. 
Here is an example how to load data from views:
https://github.com/cloudant-labs/spark-cloudant/blob/master/examples/python/CloudantDF.py#L73
