### ISSUE TITLE
unable to read large data(~2gb)

### ISSUE THREAD

**Issue by nsanthoshkumar** [cloudant-labs/spark-cloudant#66]
We are trying to read 2gb data from cloudant using the python version. We are always getting the following error.
Could you please help  us in understanding 
py4j.protocol.Py4JJavaError: An error occurred while calling o42.persist.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 24, 192.168.24.242): java.lang.ClassCastException: Cannot cast spray.http.MessageChunk to spray.http.HttpResponse
	at java.lang.Class.cast(Class.java:3369)
	at scala.concurrent.Future$$anonfun$mapTo$1.apply(Future.scala:405)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.processBatch$1(Future.scala:643)
	at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.apply$mcV$sp(Future.scala:658)
	at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.apply(Future.scala:635)
	at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.apply(Future.scala:635)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.Future$InternalCallbackExecutor$Batch.run(Future.scala:634)
	at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:685)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:266)
	at spray.can.client.HttpHostConnectionSlot.dispatchToCommander(HttpHostConnectionSlot.scala:254)
	at spray.can.client.HttpHostConnectionSlot$$anonfun$connected$1$$anonfun$applyOrElse$3$$anonfun$apply$2.apply$mcV$sp(HttpHostConnectionSlot.scala:127)
	at spray.can.client.HttpHostConnectionSlot$$anonfun$connected$1.applyOrElse(HttpHostConnectionSlot.scala:127)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at spray.can.client.HttpHostConnectionSlot.aroundReceive(HttpHostConnectionSlot.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by mayya-sharipova** [comment]
@nsanthoshkumar  Have you been able to read a smaller database? May be, a subset of your 2Gb database? 

For your big database, you can also try increase the number of partitions `jsonstore.rdd.partitions` that a database will be  divided to. An example is here: https://github.com/cloudant-labs/spark-cloudant/blob/master/examples/python/CloudantDF.py#L27

If this doesn't work, you can also try to increase this parameter here:
https://github.com/cloudant-labs/spark-cloudant/blob/master/cloudant-spark-sql/src/main/resources/reference.conf#L224. But for this, you need to rebuild spark-cloudant.jar. Instructions for building are in https://github.com/cloudant-labs/spark-cloudant/blob/master/README_build.md

**Comment by nsanthoshkumar** [comment]
@mayya-sharipova  I tried testing with a different smaller database. It works without any issue.
I changed the configuration and recompiled the spark-cloudant.jar. I am getting executors are being lost. I am not sure whether this is because of the jar or the configuration of spark

py4j.protocol.Py4JJavaError: An error occurred while calling o40.load.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 62, 192.168.24.242): ExecutorLostFailure (executor 10 lost)

**Comment by mayya-sharipova** [comment]
@nsanthoshkumar ExecutorLostFailure can occur because of many reasons (e.g. not enough memory, JAVA VM failure, timeouts, too many connections open etc..). You can check your log files to get more details on errors.

**Comment by nsanthoshkumar** [comment]
@mayya-sharipova : I tried fixing the heap memory problem. Now, i think cloudant is timing out for returning the result. Do you think increasing the https://github.com/cloudant-labs/spark-cloudant/blob/9c30527393f25715df759f54e232f7646bf5637b/cloudant-spark-sql/src/main/resources/application.conf#L22 will help me ?? Thanks for your support.

WARN TaskSetManager: Lost task 85.1 in stage 0.0 (TID 110, 192.168.24.242): java.util.concurrent.TimeoutException: Futures timed out after [900000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:107)
	at com.cloudant.spark.common.JsonStoreDataAccess.getQueryResult(JsonStoreDataAccess.scala:178)
	at com.cloudant.spark.common.JsonStoreDataAccess.getIterator(JsonStoreDataAccess.scala:119)
	at com.cloudant.spark.common.JsonStoreRDD.compute(JsonStoreRDD.scala:97)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mayya-sharipova** [comment]
@nsanthoshkumar  Yes, you can increase `requestTimeout`. But also increase the number of partitions ( you can do it in your application). This way every partition/request will load less data from Cloudant, and will require less time to complete.

**Comment by ThomTel** [comment]
hi, im facing the same issue:

**Comment by trentgd** [comment]
I know this is an old ticket, but I'm adding some info..  The root cause of the slowness is the fact that "skip" is relatively slow today in Cloudant.  So adding more partitions is unlikely to help (as more data will be scanned fully during the skip - once per partition).  So right now the best thing is to actually decrease the number of partitions as much as you can.  However, the performance of returning data per query is still not ideal, so it's a hard balance.
