### ISSUE TITLE
does this library handle http 429 errors when writing to cloudant?

### ISSUE THREAD

**Issue by snowch** [cloudant-labs/spark-cloudant#79]
I performed a quick search of this repository for the value 429 and couldn't find any matches.

Does this repository handle http 429 errors that are thrown by the new CCM model when too many requests are sent by the client? 

See here for more info:

 - https://docs.cloudant.com/bluemix.html
 - https://docs.cloudant.com/http.html#429

**Comment by HolgerKache** [comment]
Hi Chris - it does not! We have to add this in and I created a ticket (FB 79428) to capture the requirement. No word yet on when we can deliver this but let's keep the ticket open until we deliver it. Thank you for bringing it up.

**Comment by snowch** [comment]
Np, this isn't causing a problem for me so it isn't urgent from my perspective.

**Comment by snowch** [comment]
I spoke too soon :(

```
Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: Task 0 in stage 281.0 failed 10 times, most recent failure: Lost task 0.9 in stage 281.0 (TID 345, yp-spark-dal09-env5-0020): java.lang.RuntimeException: Save to Database recommendationdb_1482513622 failed with Set(Too Many Requests)
	at com.cloudant.spark.common.JsonStoreDataAccess.saveAll(JsonStoreDataAccess.scala:231)
	at com.cloudant.spark.CloudantReadWriteRelation$$anonfun$3.apply(DefaultSource.scala:86)
	at com.cloudant.spark.CloudantReadWriteRelation$$anonfun$3.apply(DefaultSource.scala:84)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1863)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1863)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:233)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
```

**Comment by snowch** [comment]
Unfortunately I can't even fall back to using the java-cloudant library for the writes because this library and the java-cloudant library share the same package com.cloudant...

**Comment by HolgerKache** [comment]
Edited by Mike Breslin 12/27/2016 3:24 PM:

To confirm, Chris encountered 429's on a write back into Cloudant database.  Currently _all_docs and _changes aren't 429'ed yet so that is why we haven't seen this issue crop up much yet.  Not sure if adding 429 retry support to writes only simplifies this as something we could do in the short-term?

**Comment by snowch** [comment]
Retrying 429's makes a lot of sense for batch jobs rather than purchasing a plan with a higher quota if you are ok with the outcome that the batch read/write will take longer to complete.  If the extra run time is not acceptable, a higher plan can be purchased. 

If we don't retry 429s, the only way to use the adapter is to increase your plan to cover the batch read/write rate but that is probably undesirable if the batch read/write is only a short job (e.g. 1 hr) because you will pay for capacity that you will not be using.  This may also be compounded because spark is able to parallelize IO, so you would have to purchase a ccm plan to cover the IO rate.

**Comment by blechner** [comment]
Hi, I have a cloudant database with some documents and I wanted to retrieve the documents in a python jupyter notebook in DSX, so I followed this [recipe](https://developer.ibm.com/recipes/tutorials/timeseries-data-analysis-of-iot-events-by-using-jupyter-notebook/) from step 5 (I skipped the previous steps because I already had a setup where device events are stored as cloudant documents). My cloudant plan is lite (free) and I am having a problem that might have something to do with that is described in this issue (this is why I didn't open a new one).
I am able to connect to the DB and print the schema, but when I run this line
```df.select("temperature").show()```
I get this error:
![image](https://user-images.githubusercontent.com/12237934/27736453-a751fdac-5d7a-11e7-9fc8-1a46e32d9884.png)

I'm new to this data science thing, spark, python, etc, so I am not sure how to fix this... is this something that can only be fixed in your spark-cloudant lib? Is there a workaround that I can do on my end? I am not sure how this job system works in spark, perhaps I can configure it to avoid running a batch of queries too fast?
I'd appreciate if you could share some insights on this.
Thanks.

**Comment by mayya-sharipova** [comment]
@blechner Hi, the project has been moved to https://github.com/apache/bahir/tree/master/sql-cloudant. 

The error you are getting is from Cloudant showing that you exceed your query limit.  You can try to decrease the number of `jsonstore.rdd.partitions` for settings, to issue less number of parallel requests.

**Comment by blechner** [comment]
Thank you very much @mayya-sharipova , I was able to get rid of the error by setting ```option("jsonstore.rdd.partitions", 4)``` in SQLContext.
