### ISSUE TITLE
nothing was saved because the number of records was 0 - when df.count() = 6

### ISSUE THREAD

**Issue by snowch** [cloudant-labs/spark-cloudant#82]
This is probably user error, but I appear to have records in my dataframe:

```
        val df = getTopXRecommendationsForAllUsers().toDF.filter( $"_1" > 6035)
          
        println(s"Saving ${df.count()} ratings to Cloudant: " + new Date())
        
        println(df.show(5))
        
        val timestamp: Long = System.currentTimeMillis / 1000
        val dbName: String = s"${destDB.database}_${timestamp}"
        
        df.write.mode("append").json(s"${dbName}.json")
        
        val dfWriter = df.write.format("com.cloudant.spark")
        dfWriter.option("cloudant.host", destDB.host)
        if (destDB.username.isDefined && destDB.username.get.nonEmpty) dfWriter.option("cloudant.username", destDB.username.get)
        if (destDB.password.isDefined && destDB.password.get.nonEmpty) dfWriter.option("cloudant.password", destDB.password.get)
        dfWriter.option("createDBOnSave", "true")
        dfWriter.save(dbName)
```

The output:

```
Starting getTopXRecommendationsForAllUsers: Sat Dec 24 08:50:11 CST 2016
Finished getTopXRecommendationsForAllUsers: Sat Dec 24 08:50:11 CST 2016
Saving 6 ratings to Cloudant: Sat Dec 24 08:50:17 CST 2016
+----+--------------------+
|  _1|                  _2|
+----+--------------------+
|6036|[[6036,2503,4.395...|
|6037|[[6037,572,4.5785...|
|6038|[[6038,1696,4.894...|
|6039|[[6039,572,4.6854...|
|6040|[[6040,670,4.6820...|
+----+--------------------+
only showing top 5 rows

()
Use connectorVersion=1.6.3, dbName=recommendationdb_1482591017, indexName=null, viewName=null,jsonstore.rdd.partitions=5, + jsonstore.rdd.maxInPartition=-1,jsonstore.rdd.minInPartition=10, jsonstore.rdd.requestTimeout=900000,bulkSize=20, schemaSampleSize=1

Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: Task 2 in stage 642.0 failed 10 times, most recent failure: Lost task 2.9 in stage 642.0 (TID 409, yp-spark-dal09-env5-0049): java.lang.RuntimeException: Database recommendationdb_1482591017: nothing was saved because the number of records was 0!
	at com.cloudant.spark.common.JsonStoreDataAccess.saveAll(JsonStoreDataAccess.scala:187)
	at com.cloudant.spark.CloudantReadWriteRelation$$anonfun$3.apply(DefaultSource.scala:86)
	at com.cloudant.spark.CloudantReadWriteRelation$$anonfun$3.apply(DefaultSource.scala:84)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1863)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1863)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:233)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
```

**Comment by snowch** [comment]
Note that for debugging purposes, I have saved to json files before trying to write to Cloudant:

```
! cat recommendationdb_1482591017.json/*

{"_1":6036,"_2":[{"user":6036,"product":2503,"rating":4.3957030284620355},{"user":6036,"product":2019,"rating":4.351395783537379},{"user":6036,"product":1178,"rating":4.3373212302468165},{"user":6036,"product":923,"rating":4.3328207761734605},{"user":6036,"product":922,"rating":4.320787353937724},{"user":6036,"product":750,"rating":4.307312349612301},{"user":6036,"product":53,"rating":4.304341611330176},{"user":6036,"product":858,"rating":4.297961629128419},{"user":6036,"product":1212,"rating":4.285360675560061},{"user":6036,"product":1423,"rating":4.275255129149407}]}
{"_1":6037,"_2":[{"user":6037,"product":572,"rating":4.578508339835482},{"user":6037,"product":858,"rating":4.247809350206506},{"user":6037,"product":904,"rating":4.1222486445799404},{"user":6037,"product":527,"rating":4.117342524702621},{"user":6037,"product":787,"rating":4.115781026855997},{"user":6037,"product":2503,"rating":4.109861422105844},{"user":6037,"product":1193,"rating":4.088453520710152},{"user":6037,"product":912,"rating":4.085139017248665},{"user":6037,"product":1221,"rating":4.084368219857013},{"user":6037,"product":1207,"rating":4.082536396283374}]}
{"_1":6038,"_2":[{"user":6038,"product":1696,"rating":4.894442132848873},{"user":6038,"product":2998,"rating":4.887752985607918},{"user":6038,"product":2562,"rating":4.740442462948304},{"user":6038,"product":3245,"rating":4.7366090605162094},{"user":6038,"product":2609,"rating":4.736125582066063},{"user":6038,"product":1669,"rating":4.678373819044571},{"user":6038,"product":572,"rating":4.606132758047402},{"user":6038,"product":1493,"rating":4.577140478430046},{"user":6038,"product":745,"rating":4.56568047928448},{"user":6038,"product":213,"rating":4.546054686400765}]}
{"_1":6039,"_2":[{"user":6039,"product":572,"rating":4.685425482619273},{"user":6039,"product":527,"rating":4.291256016077275},{"user":6039,"product":904,"rating":4.27766400846558},{"user":6039,"product":2019,"rating":4.273486883864949},{"user":6039,"product":2905,"rating":4.266371181044469},{"user":6039,"product":912,"rating":4.26006044096224},{"user":6039,"product":1207,"rating":4.259935289367192},{"user":6039,"product":2503,"rating":4.250370780277651},{"user":6039,"product":1148,"rating":4.247288578998062},{"user":6039,"product":745,"rating":4.223697008637559}]}
{"_1":6040,"_2":[{"user":6040,"product":670,"rating":4.682008703927743},{"user":6040,"product":3134,"rating":4.603656534071515},{"user":6040,"product":2503,"rating":4.571906881428182},{"user":6040,"product":3415,"rating":4.523567737705732},{"user":6040,"product":3808,"rating":4.516778146579665},{"user":6040,"product":3245,"rating":4.496176019230939},{"user":6040,"product":53,"rating":4.491020821805015},{"user":6040,"product":668,"rating":4.471757243976877},{"user":6040,"product":3030,"rating":4.464674231353673},{"user":6040,"product":923,"rating":4.446195112198678}]}
{"_1":6042,"_2":[{"user":6042,"product":3389,"rating":3.331488167984286},{"user":6042,"product":572,"rating":3.3312810949271903},{"user":6042,"product":231,"rating":3.2622287749148926},{"user":6042,"product":1439,"rating":3.0988533259613944},{"user":6042,"product":333,"rating":3.0859809743588706},{"user":6042,"product":404,"rating":3.0573976830913203},{"user":6042,"product":216,"rating":3.044620107397873},{"user":6042,"product":408,"rating":3.038302525994588},{"user":6042,"product":2411,"rating":3.0190834747311244},{"user":6042,"product":875,"rating":2.9860048032439095}]}
```

**Comment by snowch** [comment]
@HolgerKache I've shared a dsx project with you where this issue can be reproduced easily just by running the notebook - would it be possible to take a look and verify if this is a defect or not?

**Comment by snowch** [comment]
Ok, so this was a known issue with 1.6.3.  Why are we still running 1.6.3 on dsx?

**Comment by snowch** [comment]
After upgrading to spark-cloudant 1.6.4, the original error is replaced with this error:

```
Starting load from Cloudant: Wed Jan 04 07:15:41 CST 2017
Use connectorVersion=1.6.4, dbName=ratingdb, indexName=null, viewName=null,jsonstore.rdd.partitions=5, jsonstore.rdd.maxInPartition=-1,jsonstore.rdd.minInPartition=10, jsonstore.rdd.requestTimeout=900000,bulkSize=20, schemaSampleSize=-1
Finished load from Cloudant: Wed Jan 04 07:17:08 CST 2017
Found 1000005 records in Cloudant
Starting train model: Wed Jan 04 07:18:34 CST 2017
Finished train model: Wed Jan 04 07:19:10 CST 2017
Starting getTopXRecommendationsForAllUsers: Wed Jan 04 07:19:11 CST 2017
Finished getTopXRecommendationsForAllUsers: Wed Jan 04 07:19:11 CST 2017
Saving 6 ratings to Cloudant: Wed Jan 04 07:19:17 CST 2017
+----+--------------------+
|  _1|                  _2|
+----+--------------------+
|6036|[[6036,2503,4.398...|
|6037|[[6037,572,4.5697...|
|6038|[[6038,2998,4.889...|
|6039|[[6039,572,4.6928...|
|6040|[[6040,670,4.6923...|
+----+--------------------+
only showing top 5 rows

()
Use connectorVersion=1.6.4, dbName=recommendationdb_1483535957, indexName=null, viewName=null,jsonstore.rdd.partitions=5, jsonstore.rdd.maxInPartition=-1,jsonstore.rdd.minInPartition=10, jsonstore.rdd.requestTimeout=900000,bulkSize=20, schemaSampleSize=-1

Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: Task 13 in stage 732.0 failed 10 times, most recent failure: Lost task 13.9 in stage 732.0 (TID 429, yp-spark-dal09-env5-0036): akka.pattern.AskTimeoutException: Recipient[Actor[akka://CloudantSpark-c8f41dcb-596e-4ff5-9d18-c6d0295003a7/user/IO-HTTP#-1836856159]] had already been terminated.
	at akka.pattern.AskableActorRef$.ask$extension(AskSupport.scala:132)
	at akka.pattern.AskableActorRef$.$qmark$extension(AskSupport.scala:144)
	at spray.client.pipelining$$anonfun$sendReceive$1.apply(pipelining.scala:38)
	at spray.client.pipelining$$anonfun$sendReceive$1.apply(pipelining.scala:38)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at spray.httpx.TransformerPipelineSupport$WithTransformerConcatenation.apply(TransformerPipelineSupport.scala:37)
	at com.cloudant.spark.common.JsonStoreDataAccess$$anonfun$9.apply(JsonStoreDataAccess.scala:249)
	at com.cloudant.spark.common.JsonStoreDataAccess$$anonfun$9.apply(JsonStoreDataAccess.scala:245)
	at scala.concurrent.Future$$anonfun$traverse$1.apply(Future.scala:567)
	at scala.concurrent.Future$$anonfun$traverse$1.apply(Future.scala:566)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.concurrent.Future$.traverse(Future.scala:566)
	at com.cloudant.spark.common.JsonStoreDataAccess.saveAll(JsonStoreDataAccess.scala:245)
	at com.cloudant.spark.CloudantReadWriteRelation$$anonfun$3.apply(DefaultSource.scala:93)
	at com.cloudant.spark.CloudantReadWriteRelation$$anonfun$3.apply(DefaultSource.scala:91)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1863)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1863)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:233)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
```

**Comment by mayya-sharipova** [comment]
@snowch Hi Chris! Sorry for a late reply, can your please share your notebook as well as your data

**Comment by HolgerKache** [comment]
@mayya-sharipova Chris provided us with the notebook earlier and I put it in https://cloudant.fogbugz.com/f/cases/80865/

Please find it there. Thx

**Comment by mayya-sharipova** [comment]
@HolgerKache  Thanks for the update. Fb 80865 is marked as resolved. Should we resolve/close this issue here in github as well?

**Comment by cloudant-spark-service** [comment]
@Mayya I was asked to close all FB tickets in the interest of ZenHub
tracking of issues here in Git. The team no longer wants to use FB for
these sorts of libraries but the issues are still unresolved.

Can you have a look into this one using the notebook shared in that closed
FB ticket please?

Mayya Sharipova <notifications@github.com> schrieb am Mo. 16. Jan. 2017 um
21:30:

**Comment by mayya-sharipova** [comment]
@snowch The error in your case was timeout exception. We can increase timeout in spark configuration settings:
```
conf.set("jsonstore.rdd.requestTimeout", "8000000")
val sc = new SparkContext(conf)
```
But I don't think, we can modify spark configurations in running notebooks.  Another thing we can try instead is to increase `bulkSize`:
```
dfWriter.option("bulkSize", "1000")
```
Saving bigger number of records in a single request should be faster.

Please let us know if this helped to prevent the error.

**Comment by snowch** [comment]
Hi @mayya-sharipova, sorry, I just ntoiced this reply.

I used python cloudant in the end for the cloudant writes.  I'm not sure when I will get a chance to test these options, so we should probably close the ticket for now.  If anyone else hits the same problem in the future they will hopefully find this ticket via google.
