### ISSUE TITLE
mapPartitions doesn't seem to be working on the fetched data?

### ISSUE THREAD

**Issue by jokereactive** [cloudant-labs/spark-cloudant#89]
I have a simple code to fetch data from cloudant using cloudant-spark and then apply a mapPartition operation to enrich it by fetching data from some other sources. The problem I am facing is that although the map function works fine, mapPartition does not. I created a demo function to demonstrate that. Can you help out and tell me what the issue is here? 

My code is as follows - 

Snippet from main code - 
```
		self.ssqc = ssqc
		self.cloudantConnector = CloudantSparkConnector(self.ssqc, config)
		logging.debug("Fetched From Cloudant")
		self.data_rdd = self.cloudantConnector.data.toJSON().map(lambda x: json.loads(x))
		logging.debug("Converted to JSON")
		self.data_rdd_formatted = self.data_rdd.map(lambda x: {'Data':x})
		## Till this point map function works. I tested by printing the top element
                # print(self.data_rdd.formatted.take(1))
                self.data_rdd_enriched_req = self.data_rdd_formatted.mapPartitions(DemoOperation.operate)
               print(self.data_rdd_enriched_req.take(1))

```
Relevant function code - 

**CloudantSparkConnector**
```
class CloudantSparkConnector:

	def __init__(self, sqlContext, config):
		self.config = config

		self.data = sqlContext.read.format("com.cloudant.spark").\
		option("cloudant.host",self.config.getCloudantURL()).\
		option("cloudant.username",self.config.getCloudantUsername()).\
		option("cloudant.password",self.config.getCloudantPassword()).\
		load(self.config.getCloudantDBName())
```
**DemoOperation**
```
class DemoOperation:

	@staticmethod
	def fetch(data, client_id):

		logging.debug("Fetching Demo")
		final_data = []
		for row in data:
			final_data.append(row)
		logging.debug("Working")
		return final_data
```
Error I get - 
```
17/01/21 07:28:49 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in main
    process()
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/worker.py", line 167, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2371, in pipeline_func
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2371, in pipeline_func
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 317, in func
TypeError: fetch() takes exactly 2 arguments (1 given)

        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
        at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
        at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
        at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:86)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
17/01/21 07:28:49 ERROR TaskSetManager: Task 0 in stage 2.0 failed 1 times; aborting job
Traceback (most recent call last):
    print(self.data_rdd_enriched_req.take(1))
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1310, in take
    res = self.context.runJob(self, takeUpToNumLeft, p)
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/context.py", line 933, in runJob
    port = self._jvm.PythonRDD.runJob(self._jsc.sc(), mappedRDD._jrdd, partitions)
  File "/home/spark/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__

  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/home/spark/spark/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2, localhost): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in main
    process()
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/worker.py", line 167, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2371, in pipeline_func
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2371, in pipeline_func
  File "/home/spark/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 317, in func
TypeError: fetch() takes exactly 2 arguments (1 given)

**Comment by jokereactive** [comment]
Found my mistake - mapPartitions(DemoOperation.operate) should have been mapPartitions(lambda x: DemoOperation.operate(x, client_id))
